---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2022/4/13 9:46
---
require("io")

--[[
按F5执行


--]]



--[[
主要内容：
模块定义
模块调用
--]]

-- 定义一个名字为common_utils的模块
common_utils = {}

-- 定义一个常量
common_utils.constant = "这是一个常量"


-- 定义函数
function common_utils.func1()
	-- io.write("这是一个公有函数!\n")
	print("这是一个公有函数!\n")
end

-- 定义私有函数
local function func2()
	print("这是一个私有函数！")
end

-- 定义共有函数，调用私有函数
function common_utils.func3()
	func2()
end

-- 返回该模块
return common_utils

